server:
  port: 8083
spring:
  application:
    name: sboot-financeiro-back-app
  datasource:
    url: jdbc:postgresql://localhost:5432/db_financeiro
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect